class SuggestionProvider {
  static List<String> mockSuggestions = [
    "Apple"
        "Avocado"
        "Almonds"
        "Asparagus"
        "Banana"
        "Broccoli"
        "Bacon"
        "Beans"
        "Carrot"
        "Chicken"
        "Cheese"
        "Chocolate"
        "Duck"
        "Dates"
        "Dough"
        "Dragonfruit"
        "Eggplant"
        "Eggs"
        "Edamame"
        "Espresso"
        "Fish"
        "Feta"
        "Figs"
        "Flour"
        "Garlic"
        "Grapes"
        "Green Beans"
        "Ginger"
        "Ham"
        "Honey"
        "Hazelnuts"
        "Herbs"
        "Ice Cream"
        "Icing"
        "Indian spices"
        "Injera (Ethiopian flatbread)"
        "Jackfruit"
        "Jalapeno"
        "Jicama"
        "Jam"
        "Kale"
        "Kiwi"
        "Ketchup"
        "Kidney Beans"
        "Lettuce"
        "Lemon"
        "Lime"
        "Lentils"
        "Mango"
        "Mushrooms"
        "Milk"
        "Mint"
        "Noodles"
        "Nutmeg"
        "Nectarine"
        "Nuts"
        "Orange"
        "Oats"
        "Olive Oil"
        "Onion"
        "Pineapple"
        "Potatoes"
        "Peppers"
        "Peanut Butter"
        "Quinoa"
        "Quince"
        "Rice"
        "Radish"
        "Raisins"
        "Rosemary"
        "Strawberry"
        "Spinach"
        "Salmon"
        "Shrimp"
        "Tomato"
        "Tofu"
        "Turkey"
        "Thyme"
        "Udon Noodles"
        "Vanilla"
        "Vinegar"
        "Veggies"
        "Venison"
        "Watermelon"
        "Walnuts"
        "Wheat"
        "Wine"
        "Xigua"
        "Yogurt"
        "Yams"
        "Yeast"
        "Zucchini"
        "Za'atar (a Middle Eastern spice blend)"
  ];
}
